### ISSUE TITLE
Moving grunt-it to c2fo org

### ISSUE THREAD

**Issue by aheuermann** [aheuermann/grunt-it#11]
Hey Nick, we were planning on making some tweaks to grunt-it. Would it be possible to move this repo to the c2fo org and also get npm publishing rights?

**Comment by nicknisi** [comment]
Yeah, definitely! What npm user should I add as owner?

**Comment by aheuermann** [comment]
Awesome, you can add me and I will transfer it.

**Comment by nicknisi** [comment]
Yeah, I can't transfer to the c2fo org because I don't have admin access there. I added you as a collaborator on Github, and also added `aheuermann` as owner on npm.

**Comment by nicknisi** [comment]
If that doesn't work on Github, I can transfer it to you, and then you can add it to c2fo

**Comment by aheuermann** [comment]
ahh, make sense. Yeah, I can't transfer it unless I'm owner it looks like. Could you transfer to me?

**Comment by nicknisi** [comment]
requested.

**Comment by nicknisi** [comment]
Looks like it's good to go. You should be owner on npm too. Let me know if you need anything else. Thanks!

**Comment by aheuermann** [comment]
Thanks for your help!
